Repository LikeLion13th-Hackathon-cesco/cesco-FrontEnd, pull requests merged in 2025-08, with the labels that each got.

#8 refactor(#1): 스타일 가이드 색상 변수 적용
  app/components/Navbar.vue
Labels: refactor

#9 [DEPLOYMENT] AWS Amplify 테스트용 배포
  .prettierrc
  app/app.vue
  app/assets/css/global.css
  app/assets/icon/search.svg
  app/components/Hello.vue
  app/components/Navbar.vue
  eslint.config.mjs
  nuxt.config.ts
  package-lock.json
  package.json
  public/font/PretendardVariable.woff2
  server/api/hello.ts
  tailwind.config.ts
Labels: deploy

#10 actions: 배포 시 AWS Amplify 웹훅 트리거 액션 추가
  .github/workflows/amplify-deployment.yml
Labels: deploy

#12 ui(#2,#3,#4)
  app/assets/icon/commentIcon.svg
  app/assets/icon/community-uploadBtn.svg
  app/assets/icon/creditPin.svg
  app/assets/icon/divider.svg
  app/assets/icon/dropDownIcon.svg
  app/assets/icon/service-Icon.svg
  app/assets/icon/service-checkIcon.svg
  app/assets/icon/service-handIcon.svg
  app/assets/image/creditImage.jpg
  app/assets/image/pricingImage.jpg
  app/assets/image/storeImage.jpg
  app/components/BlueBtn.vue
  app/pages/credit/_components/StoreItem.vue
  app/pages/credit/creditStore.vue
  app/pages/credit/index.vue
  app/pages/map/_components/CommentItem.vue
  app/pages/map/_components/CommentWrap.vue
  app/pages/map/_components/ReplyItem.vue
  app/pages/map/index.vue
  app/pages/pricing/index.vue
  nuxt.config.ts
  package-lock.json
Labels: ui

#15 ui(#13): 체크리스트 페이지
  app/assets/image/checkFive.jpg
  app/assets/image/checkFour.jpg
  app/assets/image/checkOne.png
  app/assets/image/checkThree.jpg
  app/assets/image/checkTwo.jpg
  app/assets/image/checklistIcon.jpg
  app/pages/checklist/_components/CheckCard.vue
  app/pages/checklist/_components/CheckTipBox.vue
  app/pages/checklist/index.vue
  app/pages/map/_components/CommentItem.vue
  package-lock.json
Labels: ui

#16 UI/analyze
  app/assets/icon/check.svg
  app/assets/icon/info.svg
  app/assets/icon/trash.svg
  app/assets/icon/upload.svg
  app/assets/image/pdf-example.png
  app/pages/analyze/_components/FormPanel.vue
  app/pages/analyze/_components/PDFUploadPanel.vue
  app/pages/analyze/_modals/PdfSubmitted.vue
  app/pages/analyze/_modals/PdfUpload.vue
  app/pages/analyze/index.vue
  app/pages/checklist/credit/_components/StoreItem.vue
  app/pages/checklist/credit/creditStore.vue
  app/pages/checklist/credit/index.vue
  app/stores/file.ts
  package-lock.json
  package.json
Labels: ui

#28 api(#27): 마이페이지 api 연동
  app/pages/my/_api/types/MyPageResponse.ts
  app/pages/my/index.vue
Labels: api

#35 ui(#17): 분석 절차 및 유의사항 퍼블리싱
  app/assets/icon/analysis-step-1.svg
  app/assets/icon/analysis-step-2.svg
  app/assets/icon/analysis-step-3.svg
  app/assets/icon/analysis-step-4.svg
  app/assets/icon/chevron-right-blue.svg
  app/assets/image/alien.png
  app/pages/analyze/result/_components/ProcessAndDisclaimer.vue
  app/pages/analyze/result/_components/ProcessStep.vue
  app/pages/analyze/result/index.vue
  app/pages/index.vue
Labels: ui

#36 [API] 커뮤니티 댓글
  app/assets/icon/filledHeart.svg
  app/assets/icon/sendCommentIcon.svg
  app/composables/useDebounce.ts
  app/pages/community/_api/types/PostResponse.ts
  app/pages/community/_api/types/SearchAddressResponse.ts
  app/pages/community/_components/CommentItem.vue
  app/pages/community/_components/CommentWrap.vue
  app/pages/community/_components/PostReply.vue
  app/pages/community/_components/ReplyItem.vue
  app/pages/community/_components/SearchBar.vue
  app/pages/community/_modals/PostComment.vue
  app/pages/community/_utils/splitByKeyword.ts
  app/pages/community/index.vue
  package-lock.json
  package.json
Labels: api

#38 api(#36): 커뮤니티 댓글 api 응급 수술 완료
  app/pages/community/_api/types/ReplyResponse.ts
  app/pages/community/_components/CommentItem.vue
  app/pages/community/_components/CommentWrap.vue
  app/pages/community/_components/ReplyItem.vue
  app/pages/community/_modals/PostComment.vue
  package-lock.json
Labels: api

#46 api(#29): 분석 페이지 API 연동 완료
  app/pages/analyze/_api/types/AnalyzeSubmitResponse.ts
  app/pages/analyze/_components/FormPanel.vue
  app/pages/analyze/_modals/PdfSubmitted.vue
  app/pages/analyze/_modals/PdfUpload.vue
  app/pages/analyze/_utils/calculations.ts
  app/pages/analyze/_utils/formSchema.ts
  app/pages/analyze/index.vue
  app/pages/analyze/result/[id]/_components/ProcessAndDisclaimer.vue
  app/pages/analyze/result/[id]/_components/ProcessStep.vue
  app/pages/analyze/result/[id]/index.vue
Labels: api

#53 Qa/credit
  app/assets/image/amisan.jpg
  app/assets/image/flowerGimbap.jpg
  app/assets/image/victorySuper.jpg
  app/pages/checklist/_components/CheckCard.vue
  app/pages/checklist/_components/CheckTipBox.vue
  app/pages/checklist/index.vue
  app/pages/community/_components/CommentItem.vue
  app/pages/community/_components/CommentWrap.vue
  app/pages/community/_components/PostReply.vue
  app/pages/community/_components/ReplyItem.vue
  app/pages/community/_components/SearchBar.vue
  app/pages/community/_modals/PostComment.vue
  app/pages/community/index.vue
  app/pages/credit/_components/StoreItem.vue
  app/pages/credit/creditStore.vue
  app/pages/report/_components/Upload.vue
  app/pages/report/_modals/UploadComplete.vue
  app/pages/report/index.vue
Labels: qa
